version: "3"

services:
  postgres:
    container_name: sento_api_db
    image: geographica/postgis:spry_sparrow
    volumes:
      - sento-data:/data
      - ./sento_api/database/init.sql:/src/init.sql
    env_file:
      - db.env

volumes:
  sento-data:
    external: true
